# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

# Run this workflow every time a new commit is pushed to the 'main' branch
on:
  push:
    branches: [ master ]

# Jobs to be executed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # 2. (Optional) If you need to build your site first (e.g., with Node.js)
      #    Uncomment the following lines if your project needs a build step.
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Install dependencies
      #   run: npm install
      # - name: Build project
      #   run: npm run build # Or your build command, which should create the 'public' folder

      # 3. Deploys the specified folder to the 'gh-pages' branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # This is the secret token provided by GitHub Actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is the directory to publish
          publish_dir: ./public
